### ISSUE TITLE
Different quantitive results between the paper and the leaderboard on SMIYC dataset

### ISSUE THREAD

**Issue by cuttle-fish-my** [NazirNayal8/RbA#14]
Hi, thanks to your effort on this fantastic work! I notice that the quantitive results of SMIYC dataset in paper is as following:
<img width="1201" alt="image" src="https://github.com/user-attachments/assets/363a554b-9f52-414e-be37-42ab3d8d0b0f">
But in the [leaderboard of SMIYC](https://segmentmeifyoucan.com/leaderboard), the results of Rba has been boosted significantly(see the following figures):
<img width="903" alt="image" src="https://github.com/user-attachments/assets/eca8e680-afde-4039-a100-3a10f50d273c">
<img width="886" alt="image" src="https://github.com/user-attachments/assets/c39bb88e-ba96-4796-854c-e3a5b7a52834">
I'm wondering where did the improvements come from? Have you updated the results with [RbA + Mapillary + COCO Outlier Supervision](https://github.com/NazirNayal8/RbA/blob/main/MODEL_ZOO.md#rba--mapillary--coco-outlier-supervision)?

Thanks in advance and looks forward to your replay!

**Comment by NazirNayal8** [comment]
Greetings @cuttle-fish-my ,

Thank you for you interest in our work. The results on the SMIYC benchmark are for the models trained using mapillary as additional training data. We added a table in the paper that shows these results in the supplementary:

https://openaccess.thecvf.com/content/ICCV2023/supplemental/Nayal_RbA_Segmenting_Unknown_ICCV_2023_supplemental.pdf

**Comment by cuttle-fish-my** [comment]
Thanks!
