### ISSUE TITLE
Question about train and finetune

### ISSUE THREAD

**Issue by wyz22966** [NazirNayal8/RbA#16]
Hi, thanks to your effort on this fantastic work!
I encountered some difficulties while reproducing the experiment.
I am planning to train Swin-B  on the Cityscapes dataset and finetune it on coco and mapillary,
`python train_net.py \
--config-file configs/cityscapes/semantic-segmentation/swin/single_decoder_layer/maskformer2_swin_base_IN21k_384_bs16_90k_1dl.yaml \
--num-gpus 1 SOLVER.IMS_PER_BATCH 8\
OUTPUT_DIR  model_logs/swin_b_1dl/`
I obtained model_final.pth using the aforementioned code. How should I proceed with fine-tuning it next?

**Comment by NazirNayal8** [comment]
Hi @wyz22966 , 

Thank you for your interest in our work. We provide a config file that you can use to finetune on COCO and mapillary. You can find it [here](https://github.com/NazirNayal8/RbA/blob/main/ckpts/swin_b_1dl_rba_ood_map_coco/config.yaml).

You can simply run where `CONFIG` is the path to the config file linked above:
```
python train_net.py --config-file CONFIG
```
This should exactly replicate the finetuning experiment. Make sure user-specific values, such as dataset  paths, output paths ...etc are overwritten in the config file to match your setup.

I hope this was helpful. If you have anymore issues please write here in the issue again.

**Comment by wyz22966** [comment]
Hello, thank you very much for your reply.
`python train_net.py --config-file ckpts/swin_b_1dl_rba_ood_map_coco/config.yaml --num-gpus 1`
I encountered an error at the end of using the above code, but I still got the fine tuned 'model_final.pth'
![error](https://github.com/user-attachments/assets/9d9d2064-45b0-4af3-ab30-00f3e88788da)
I will put the  PTH file into CKPTS/,and then evaluate it.
`python evaluate_ood.py --out_path results_test/only_finetune/ --models_folder ckpts --datasets_folder datasets/  --dataset_mode all --store_anomaly_scores`
the results are as follows:

![1](https://github.com/user-attachments/assets/47feeb57-9a30-495d-beb2-3ec193386dfb)
![finetune](https://github.com/user-attachments/assets/1c015b18-de7a-40b0-a372-38526f54cf38)
Thanks again for your help.
